---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: messaging
  description: Messaging platform (KAFKA)
  tags:
    - kafka
  links:
    - url: https://kafka.apache.org/20/documentation.html
      title: Apache Kafka documentaion
  annotations:
    gitlab.com/project-id: "25375882"
    newrelic.com/dashboard-guid: NDA4ODYwMHxWSVp8REFTSEJPQVJEfGRhOjIzOTQzNQ
    backstage.io/adr-location: adrs
    backstage.io/techdocs-ref: dir:../../../
spec:
  type: service
  lifecycle: production
  owner: team-messaging-1
  providesApis:
    - messaging-kafka-connector-api
  dependsOn:
    - resource:default/messaging-kafka-zookeepers
    - resource:default/messaging-kafka-brokers
  system: Messaging
